# Generated by Django 6.0.4 on 2026-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'تيشرت'), ('pants', 'بنطلون'), ('shirt', 'قميص')], default='tshirt', max_length=20, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'متوفر'), ('out_of_stock', 'نفذت الكمية'), ('last_piece', 'أخر قطعة')], default='available', max_length=20, verbose_name='حالة المنتج'),
        ),
    ]
